export const skills = [
  { name: 'C#', icon: 'logos:c-sharp', color: 'from-purple-500 to-purple-600' },
  { name: 'Flutter', icon: 'logos:flutter', color: 'from-purple-400 to-purple-500' },
  { name: 'Dart', icon: 'logos:dart', color: 'from-purple-500 to-purple-600' },
  { name: 'JavaScript', icon: 'logos:javascript', color: 'from-purple-400 to-purple-600' },
  { name: 'TypeScript', icon: 'logos:typescript-icon', color: 'from-purple-500 to-purple-600' },
  { name: 'Astro', icon: 'logos:astro', color: 'from-purple-500 to-purple-600' },
  { name: 'Tailwind', icon: 'logos:tailwindcss-icon', color: 'from-purple-400 to-purple-500' },
  { name: 'CSS', icon: 'logos:css-3', color: 'from-purple-500 to-purple-600' },
  { name: 'PostgreSQL', icon: 'logos:postgresql', color: 'from-purple-500 to-purple-600' },
  { name: 'Python', icon: 'logos:python', color: 'from-purple-500 to-purple-600' },
  { name: 'Java', icon: 'logos:java', color: 'from-purple-500 to-purple-600' },
  { name: 'Next.js', icon: 'logos:nextjs-icon', color: 'from-purple-500 to-purple-600' },
  { name: 'React', icon: 'logos:react', color: 'from-purple-500 to-purple-600' },
];
